Repository XREAL-SNU/xTown, pull requests merged in 2022-02, with the labels that each got.

#94 #74 Client Tools StickyNote Jinhong
  Assets/Prefabs/StickyNote/StickyNoteButtonCanvas.prefab
  Assets/Prefabs/StickyNote/StickyNoteButtonCanvas.prefab.meta
  Assets/Resources/StickyNote.meta
  Assets/Resources/StickyNote/StickyNoteDetailCanvas.prefab
  Assets/Resources/StickyNote/StickyNoteDetailCanvas.prefab.meta
  Assets/Resources/StickyNote/StickyNotePrefab.prefab
  Assets/Resources/StickyNote/StickyNotePrefab.prefab.meta
  Assets/Scenes/StickyNote_Jinhong.unity
  Assets/Scripts/StickyNote_Jinhong/ContentCanvas.cs
  Assets/Scripts/StickyNote_Jinhong/ContentCanvas.cs.meta
  Assets/Scripts/StickyNote_Jinhong/ContentRotator.cs
  Assets/Scripts/StickyNote_Jinhong/ContentScaler.cs
  Assets/Scripts/StickyNote_Jinhong/ControllerCanvas.cs
  Assets/Scripts/StickyNote_Jinhong/ControllerCanvas.cs.meta
  Assets/Scripts/StickyNote_Jinhong/DragableUI.cs
  Assets/Scripts/StickyNote_Jinhong/EditCanvas.cs
  Assets/Scripts/StickyNote_Jinhong/EditCanvas.cs.meta
  Assets/Scripts/StickyNote_Jinhong/RadialProgress.cs
  Assets/Scripts/StickyNote_Jinhong/RadialProgress.cs.meta
  Assets/Scripts/StickyNote_Jinhong/StickyNote.cs
  Assets/Scripts/StickyNote_Jinhong/StickyNoteButton.cs
  Assets/Scripts/StickyNote_Jinhong/StickyNoteCanvas.cs
  Assets/Scripts/StickyNote_Jinhong/StickyNoteCanvas.cs.meta
  Assets/StaticAssets/StickyNote/Textures/RingCircle.png
  Assets/StaticAssets/StickyNote/Textures/RingCircle.png.meta
  Assets/StaticAssets/StickyNote/Textures/circle.png
  Assets/StaticAssets/StickyNote/Textures/circle.png.meta
  Assets/StaticAssets/StickyNote/Textures/x mark.png
  Assets/StaticAssets/StickyNote/Textures/x mark.png.meta
Labels: 클라이언트팀

#133 아바타 커스터마이징_IntoDev(TaeHo)
  Assets/Resources/CharacterPrefab.prefab
  Assets/Resources/Customizingbutton.prefab
  Assets/Resources/Customizingbutton.prefab.meta
  Assets/Resources/UI/Scene/Canvases.prefab
  Assets/Resources/UI/Scene/CustomizingOther.prefab
  Assets/Resources/UI/SubItem/CustomizingButton2.prefab
  Assets/Resources/UI/SubItem/CustomizingButton2.prefab.meta
  Assets/Resources/UI/SubItem/CustomizingPage.prefab
  Assets/Resources/UI/SubItem/CustomizingTab.prefab
  Assets/Resources/fcpButton.prefab
  Assets/Resources/fcpButton.prefab.meta
  Assets/Scenes/Lobby.unity
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarCameraScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarCameraScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/ColorElement.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/ColorElement.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/CustomizablePart.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/CustomizablePart.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/TextureElement.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/AvatarClass/TextureElement.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/ColorButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/ColorButtonScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingButton.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingButtonGroup.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingButtonScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingOther.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingPage.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingPanelScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingPanelScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingPanelScript2.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/CustomizingPanelScript2.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/RandomButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/RandomButtonScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/ResetButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/ResetButtonScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/TextureButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/TextureButtonScript.cs.meta
  Assets/Scripts/Lobby/UI/AvatarCustomization/fcpButtonScript.cs
  Assets/Scripts/Lobby/UI/AvatarCustomization/fcpButtonScript.cs.meta
  Assets/Scripts/Player/AvatarAppearanceNew.cs
  Assets/Scripts/Player/Palette.cs
  Assets/StaticAssets/CartoonSpaceSuit/Materials/Face.mat
  Assets/StaticAssets/CartoonSpaceSuit/Prefabs/CartoonSpaceSuitPrefab.prefab
Labels: 클라이언트팀, 아바타팀

#138 #135 StickyNote Minor Fixes
  Assets/Prefabs/StickyNote/StickyNotePrefab.prefab
  Assets/Resources/StickyNotePrefab.prefab
  Assets/Scripts/StickyNote/ContentCanvas.cs
  Assets/Scripts/StickyNote/ControllerCanvas.cs
  Assets/StaticAssets/StickyNote/Textures/CotyToColiboardIcon.png
  Assets/StaticAssets/StickyNote/Textures/CotyToColiboardIcon.png.meta
  Assets/StaticAssets/StickyNote/Textures/ExportToTxtIcon.png
  Assets/StaticAssets/StickyNote/Textures/ExportToTxtIcon.png.meta
Labels: 클라이언트팀

#149 #148 StickyNote Minor Fix
  Assets/Scripts/StickyNote/StickyNoteButton.cs
Labels: 클라이언트팀

#160 [feat] voice chat mute other player in list
  Assets/Prefabs/Chat/AttachOnPlayer/ChatStatusCanvas.prefab
  Assets/Prefabs/Chat/Voice.prefab
  Assets/Prefabs/UI/MainRoom/MainCanvases.prefab
  Assets/Resources/CharacterPrefab.prefab
  Assets/Resources/UI/Popup/VoiceChatChannelsPopup.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scenes/MainRoom.unity
  Assets/Scripts/AudioChat/AudioChatUserListing.cs
  Assets/Scripts/AudioChat/PlayerVoice.cs
  Assets/Scripts/AudioChat/PlayerVoice.cs.meta
  Assets/Scripts/AudioChat/VoiceChatToggle.cs
  Assets/Scripts/AudioChat/VoiceChatToggle.cs.meta
  Assets/Scripts/AudioChat/VoiceSprites.cs
  Assets/Scripts/MainRoom/UI/MainCanvas.cs
  Assets/Scripts/MainRoom/UI/VoiceChatButton.cs
  Assets/Scripts/MainRoom/UI/VoiceChatButton.cs.meta
Labels: 네트워크팀

#161 [feat] avatar face sync
  Assets/Prefabs/Chat/AttachOnPlayer/Speaker.prefab
  Assets/Resources/CharacterPrefab.prefab
  Assets/Resources/CharacterPrefabPreview.prefab
  Assets/Resources/ForSetAvatar/CharacterPrefab.prefab
  Assets/Scripts/Common/Debug.meta
  Assets/Scripts/Common/Debug/GUILogger.cs
  Assets/Scripts/Common/Debug/GUILogger.cs.meta
  Assets/Scripts/Player/AvatarAppearanceNew.cs
  Assets/Scripts/Player/AvatarFaceControl.cs
  Assets/Scripts/Player/Emotion.cs
  Assets/Scripts/Player/PlayerAvatar.cs
  Assets/StaticAssets/CartoonSpaceSuit/Materials/Face.mat
  Assets/StaticAssets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
Labels: 네트워크팀

#165 [FIX] Avatar_faceCamera
  Assets/Resources/CharacterPrefab.prefab
  Assets/Scenes/MainRoom.unity
  Assets/Scripts/MainRoom/CamManager.cs
  Assets/Scripts/MainRoom/CameraControl.cs
  Assets/Scripts/Player/Emotion.cs
  ProjectSettings/TagManager.asset
Labels: 클라이언트팀, 아바타팀

#168 0215_playerinput lock
  Assets/Prefabs/ChatManager1 1.prefab
  Assets/Prefabs/InputManager.prefab
  Assets/Prefabs/InputManager.prefab.meta
  Assets/Prefabs/UI/MainRoom/MainCanvases.prefab
  Assets/Resources/StickyNotePrefab.prefab
  Assets/Scenes/MainRoom.unity
  Assets/Scripts/MainRoom/CamManager.cs
  Assets/Scripts/MainRoom/CameraControl.cs
  Assets/Scripts/MainRoom/InputManager.cs
  Assets/Scripts/MainRoom/InputManager.cs.meta
  Assets/Scripts/Player/AvatarFaceControl.cs
  Assets/Scripts/Player/Emotion.cs
  Assets/Scripts/Player/PlayerInput.cs
  Assets/Scripts/Player/PlayerInput.cs.meta
  Assets/Scripts/TextChat/PlayerInputLock.cs
  Assets/Scripts/TextChat/PlayerInputLock.cs.meta
  Assets/StaticAssets/StarterAssets/InputSystem/StarterAssetsInputs.cs
Labels: 아바타팀

#171 0215_playerinputlock
  Assets/Prefabs/UI/MainRoom/MainCanvases.prefab
  Assets/Scenes/MainRoom.unity
  Assets/Scripts/MainRoom/CamManager.cs
  Assets/Scripts/MainRoom/CameraControl.cs
  Assets/Scripts/MainRoom/InputManager.cs
  Assets/Scripts/MainRoom/UI/WorldMinimap.cs
  Assets/Scripts/Player/AvatarFaceControl.cs
  Assets/Scripts/Player/EmoticonMenuScript.cs
  Assets/Scripts/Player/Emotion.cs
  Assets/Scripts/Player/PlayerInput.cs
  Assets/Scripts/TextChat/PlayerInputLock.cs
  Assets/StaticAssets/StarterAssets/InputSystem/StarterAssetsInputs.cs
Labels: 클라이언트팀, 아바타팀

#192 #156 Avatar Random Animations
  Assets/Resources/CharacterPrefab.prefab
  Assets/StaticAssets/StarterAssets/InputSystem/StarterAssets.inputactions
  Assets/StaticAssets/StarterAssets/InputSystem/StarterAssetsInputs.cs
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Cheering.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Cheering.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Clapping.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Clapping.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Crawling.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Crawling.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Hip Hop Dancing 2.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Hip Hop Dancing 2.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Hip Hop Dancing.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Hip Hop Dancing.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Joyful Jump.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Joyful Jump.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Lead Jab.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Lead Jab.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Shopping Cart Dance.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Shopping Cart Dance.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Silly Dancing.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Silly Dancing.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Standing Greeting.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Standing Greeting.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Walking.fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Walking.fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Waving (1).fbx
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/Random Animations/Waving (1).fbx.meta
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Character/Animations/StarterAssetsThirdPerson.controller
  Assets/StaticAssets/StarterAssets/ThirdPersonController/Scripts/ThirdPersonController.cs
Labels: 클라이언트팀
